// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czefzetobujokqjhhtpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6ZWZ6ZXRvYnVqb2txamhodHBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMzU0ODQsImV4cCI6MjA1NzYxMTQ4NH0.8ubYlnnvMyxcFEJ6VbhwuigMXaAYe2lGPsFsNCa8qHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);